### ISSUE TITLE
Assistant not processing anything

### ISSUE THREAD

**Issue by navanchauhan** [vanshg/MacAssistant#36] opened 2018-01-10 08:01 UTC
There are no further instructions on compiling or how to run the project after copying the json file

**Comment by vanshg** [comment] 2018-01-10 17:15
You should just be able to hit the Run/Play button in Xcode

**Comment by navanchauhan** [comment] 2018-01-11 09:18
But nothing happens, it throws 4 error and which scheme shall I build?

**Comment by navanchauhan** [comment] 2018-01-11 11:07
<img width="1512" alt="screen shot 2018-01-11 at 4 35 58 pm" src="https://user-images.githubusercontent.com/29234112/34822621-962a338e-f6ed-11e7-8278-4213fa04e583.png">

**Comment by navanchauhan** [comment] 2018-01-11 11:08
And When I press the play button 
<img width="1512" alt="screen shot 2018-01-11 at 4 38 31 pm" src="https://user-images.githubusercontent.com/29234112/34822713-e020a090-f6ed-11e7-9156-d2c21439ea85.png">

**Comment by navanchauhan** [comment] 2018-01-11 11:13
<img width="1512" alt="screen shot 2018-01-11 at 4 42 38 pm" src="https://user-images.githubusercontent.com/29234112/34822917-84b82e66-f6ee-11e7-9bde-d6915cd4dbfa.png">
The Build is Failing :

**Comment by navanchauhan** [comment] 2018-01-11 11:21
NOTE : it was also throwing an error of 'google_oauth_dev.json is missing' So I made a copy of google_oauth and renamed it to match it. It compiledn

**Comment by navanchauhan** [comment] 2018-01-11 11:23
New Error : 
<img width="501" alt="screen shot 2018-01-11 at 4 53 20 pm" src="https://user-images.githubusercontent.com/29234112/34823321-f6e3175c-f6ef-11e7-99fd-45a86e7b28f0.png">

**Comment by navanchauhan** [comment] 2018-01-11 11:33
I hear the sound on pressing the mic but nothing happens after that, it doesn't process my commands
Code after pressing the dots 
```

[2018-01-11 17:02:07.497] AppDelegate.swift:106 INFO: Showing popover
[2018-01-11 17:02:10.148] API.swift:77 DEBUG: Call completed
[2018-01-11 17:02:10.149] API.swift:137 ERROR: Initial receive error endOfStream The operation couldn’t be completed. (MacAssistant.Google_Assistant_Embedded_V1Alpha2_EmbeddedAssistantClientError error 1.)
[2018-01-11 17:02:20.341] API.swift:99 INFO: Closed send
[2018-01-11 17:02:20.342] API.swift:108 ERROR: close catch tooManyOperations The operation couldn’t be completed. (gRPC.CallError error 8.)
[2018-01-11 17:02:20.342] API.swift:137 ERROR: Initial receive error endOfStream The operation couldn’t be completed. (MacAssistant.Google_Assistant_Embedded_V1Alpha2_EmbeddedAssistantClientError error 1.)

```

**Comment by vanshg** [comment] 2018-01-12 06:34
Duplicate of https://github.com/vanshg/MacAssistant/issues/32

**Closed by vanshg** 2018-01-12 06:34 UTC
