### ISSUE TITLE
possibility to use keyboard

### ISSUE THREAD

**Issue by jordyvandomselaar** [vanshg/MacAssistant#49] opened 2018-07-04 11:27 UTC
When at work it'd be weird if I started talking to my laptop. It'd be awesome if I could type my queries to the assistant, like you can on the phone.

**Comment by andrewdavidmackenzie** [comment] 2018-07-04 19:44
I had the same thought and considered looking into it. 

As in some situations you don't want to speak or have others hear some queries.

The ideal would be a small text box on the dialog that opens from the Mac menu or via keyboard shortcut.

**Comment by Stvad** [comment] 2018-07-15 19:36
Came here searching for this :) It'd be great! As a follow-up - integration with Alfred can be considered.

**Comment by jubby2000** [comment] 2018-10-04 19:14
Duplicate of #4

**Comment by vanshg** [comment] 2018-10-28 22:39
This should be working now!

**Closed by vanshg** 2018-10-28 22:39 UTC
